auto: true
markdown: rdiscount
permalink: /:year/:month/:day/:title
rdiscount extensions: [smart]

author: "Russell Schmidt"
email: hey@russellschmidt.net

google_analytics: "UA-65699622-1"

twitter_username: rustiest
github_username:  russellschmidt
linkedin_username: russellschmidt
facebook_username: RussellMSchmidt